#!/usr/bin/env bash
# This script tells the story of /etc/passwd using a counter for gang number.
count=0
while IFS=: read -r username password _ _ _ home shell; do
  echo "The user $username is part of the ${count} gang, lives in $home and rides $shell. ${count}'s place is protected by the passcode $password, more info about the user here: $username"
  count=$((count+1))
done < /etc/passwd
