#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code from the Apache log file

awk '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -rn | awk '{print $1+0, $2, $3}'
