#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code from Apache log file
# Displays data ordered by occurrence number (from greatest to lowest)

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn | sed 's/^[ ]*//' | awk '{print $1" "$2" "$3}'
